include:
  template: Verify/Browser-Performance.gitlab-ci.yml

variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build
  - deploy
  - performance

build:
  image: node:16.15.0
  stage: build
  script:
    - npm install
    - npm run build:client
    - npm run build:server
  artifacts:
    expire_in: 1 week
    paths:
      - dist
      - node_modules

deploy:
  image: node:16.15.0
  stage: deploy
  only:
    - main
  script:
    - apt-get update
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$PRIVATE_KEY")
    - ssh -p22 $USER@$HOST "mkdir -p $DEPLOY_PATH/tmp"
    - ssh -p22 $USER@$HOST "touch $DEPLOY_PATH/tmp/restart.txt"
    - ssh -p22 $USER@$HOST "mkdir -p $DEPLOY_PATH/_dist"
    - ssh -p22 $USER@$HOST "mkdir -p $DEPLOY_PATH/_node_modules"
    - scp -P22 -r dist/* $USER@$HOST:$DEPLOY_PATH/_dist
    - scp -P22 -r node_modules/* $USER@$HOST:$DEPLOY_PATH/_node_modules
    - ssh -p22 $USER@$HOST "rm -rf $DEPLOY_PATH/dist && rm -rf $DEPLOY_PATH/node_modules"
    - ssh -p22 $USER@$HOST "mv $DEPLOY_PATH/_dist $DEPLOY_PATH/dist && mv $DEPLOY_PATH/_node_modules $DEPLOY_PATH/node_modules"

browser_performance:
  variables:
    URL: https://www.christian-doering.de